#!/bin/sh

# drushcommand="ddev drush";
drushcommand='vendor/bin/drush';

modules=(
  # Modulos Drupal para migracion
  migrate_upgrade
  migrate_drupal_ui
  migrate_plus
  migrate_tools
  migrate_upgrade
  migrate_devel
  views_migration
  migrate_url2link
  migrate_file_to_media
  webform_migrate
  field_group_migrate
  # Modulos que estaban en el sitio Drupal 7
  media
  address
  telephone
  publishcontent
  datetime_range
  admin_toolbar
  adminimal_admin_toolbar
  # audit_log
  auto_entitylabel
  # ddev drush en -y backup_migrate
  better_exposed_filters
  block_class
  captcha
  fullcalendar_view
  colorbox
  context
  context_ui
  diff
  entityqueue
  config_split
  feeds
  field_group
  field_formatter_class
  field_permissions
  paragraphs
  file_resup
  flood_control
  fontawesome
  forum
  fivestar
  advagg
  advagg_bundler
  advagg_mod
  advagg_css_minify
  advagg_js_minify
  autologout
  cacheexclude
  charts
  charts_google
  charts_highcharts
  computed_field
  geofield
  geocoder
  geocoder_autocomplete
  google_analytics_counter
  hacked
  imce
  image_field_caption
  inline_entity_form
  insert
  leaflet
  libraries
  login_emailusername
  mailsystem
  smtp
  media_bulk_upload
  metatag
  metatag_facebook
  metatag_google_cse
  metatag_google_plus
  metatag_mobile
  metatag_twitter_cards
  metatag_verification
  metatag_views
  metatag_favicons
  metatag_hreflang
  metatag_open_graph
  metatag_open_graph_products
  module_filter
  menu_link_attributes
  menu_item_extras
  nice_menus
  panels
  pathauto
  plupload
  purge
  quicktabs
  roleassign
  rules
  search404
  search_api
  search_api_glossary
  search_api_autocomplete
  search_api_sorts
  search_api_spellcheck
  search_api_solr
  search_api_db
  search_api_synonym
  search_api_attachments
  seckit
  security_review
  slick
  slick_ui
  slick_devel
  slick_extras
  slick_views
  statistics
  taxonomy_manager
  taxonomy_menu
  taxonomy_menu_ui
  term_reference_tree
  token
  varnish
  video
  view_unpublished
  views
  views_autocomplete_filters
  views_bootstrap
  views_bulk_operations
  views_conditional
  views_contextual_filters_or
  views_data_export
  views_field_view
  views_infinite_scroll
  views_natural_sort
  views_slideshow
  views_fieldsets
  views_timelinejs
  views_flexbox
  votingapi
  webform
  webform_ui
  webform_analysis
  xmlsitemap
  youtube
  geophp
  recaptcha
  devel
  config_translation
  content_translation
  dashboard
  date_popup
  sitemap
  facets
  facets_exposed_filters
  field_validation
  google_analytics
  shs
  image_effects
  scheduler
  bootstrap_quicktabs
  bootstrap_layouts
  bootstrap_layout_builder
  doe
  panelizer
  job_scheduler
  # we_megamenu
  page_manager
  php
  poll
  rdf
  easy_breadcrumb
  pdf_using_mpdf
  page_manager_ui
  purge_ui
  geocoder_geofield
  geofield_map
)

for module_name in "${modules[@]}"; do
  $drushcommand en -y "$module_name"
done
