<?php

use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\layout_builder\SectionComponent;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implementa hook_block_view_alter().
 */
function icbf_migrations_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if (empty($args[0])) {
    $view_id = $view->id();
    $args = [];
    // Get the arguments for nodes.
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      $node_id = $node->id();
      $layout_configs = \Drupal::database()->select('node__layout_builder__layout', 'nl')
        ->fields('nl', ['layout_builder__layout_section'])
        ->condition('entity_id', $node_id)
        ->execute()->fetchAll();
    }
    else {
      $term = \Drupal::routeMatch()->getParameter('taxonomy_term');
      if ($term instanceof \Drupal\taxonomy\Entity\Term ) {
        $term_id = $term->id();
        $layout_configs = \Drupal::database()->select('taxonomy_term__layout_builder__layout', 'tl')
          ->fields('tl', ['layout_builder__layout_section'])
          ->condition('entity_id', $term_id)
          ->execute()->fetchAll();
      }
    }

    if (!empty($layout_configs)) {
      $cid = 'views_processed';
      $cache_data = \Drupal::cache()->get($cid)->data ?? [];

      foreach ($layout_configs as $layout_config) {
        // @see Drupal\layout_builder\Section
        $layout_config = $layout_config->layout_builder__layout_section;
        $layout_config = unserialize($layout_config);
        $layout_components = $layout_config->getComponents();
        foreach ($layout_components as $comp_uuid => $component) {
          $args = [];
          $component_config = $component->get('configuration');
          if ($component_config['id'] == "views_block:{$view->id()}-{$display_id}") {
            if (!in_array($comp_uuid, $cache_data)) {
              if (!empty($component_config['arguments'])) {
                $cache_data[$comp_uuid] = $comp_uuid;
                \Drupal::cache()->set($cid, $cache_data, time() + 10);
                foreach ($component_config['arguments'] as $block_argument) {
                  $args[] = $block_argument;
                }
              }
              break 2;
            }
          }
        }
      }
    }
    elseif (empty($layout_configs) && $term) {
      $vocabulary = $term->bundle();
      $items_per_page = $view->getItemsPerPage();
      $config_display = \Drupal::database()->select('config', 'c')
        ->fields('c', ['data'])
        ->condition('name', "core.entity_view_display.taxonomy_term.{$vocabulary}.default")
        ->execute()->fetchAll();

      foreach ($config_display as $config_value) {
        $layout_config = $config_value->data;
        $layout_config = unserialize($layout_config);
        if (isset($layout_config['third_party_settings']['layout_builder']['sections'])) {
          $sections = $layout_config['third_party_settings']['layout_builder']['sections'];
          foreach ($sections as $section) {
            if (isset($section['components'])) {
              foreach ($section['components'] as $component) {
                if ($component['configuration']['id'] == "views_block:{$view_id}-{$display_id}" && $component['configuration']['items_per_page'] == $items_per_page) {
                  if (!empty($component['configuration']['items_per_page'])) {
                    $filters = explode('/', $component['configuration']['items_per_page']);
                    foreach ($filters as $filter_value) {
                      if ($filter_value == '%tid') {
                        $args[] = $term_id;
                      }
                      else {
                        $args[] = $filter_value;
                      }
                    }
                  }

                  break 2;
                }
              }
            }
          }
        }
      }
    }
  }

  // Only for SIGE Process View.
  if ($view->id() == 'sige_process' && $display_id == 'block_4') {
    $url = explode('/', \Drupal::service('path.current')->getPath());
    $term_id = $url[3];
    $vocabulary = 'sige_process_type';
    $children = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree(
      $vocabulary,
      $term_id,
    );

    if (empty($children)) {
      $args[] = 'all';
    }
    else {
      $terms = [];
      foreach ($children as $term) {
        $terms[] = $term->tid;
      }
      $args[] = implode(',', $terms);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function icbf_migrations_form_layout_builder_update_block_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'layout_builder_') !== FALSE) {
    if (isset($form['settings']['provider']['#type']) && $form['settings']['provider']['#value'] === 'views') {
      $build_info = $form_state->getBuildInfo();

      if (!empty($build_info['args'][0])) {
        /** @var \Drupal\layout_builder\SectionComponent $component */
        $section_storage = $build_info['args'][0];

        $arguments = $form['settings']['views_label']['#description']->getArguments();
        $url  = explode('/', $arguments[':url']);
        $view_id = $url[5];
        $display_id = $url[7];

        foreach ($section_storage->getSections() as $section) {
          foreach ($section->getComponents() as $component) {
            $component_id = $component->getPluginId();
            if ($component_id === "views_block:{$view_id}-{$display_id}") {
              $form['settings']['override']['items_per_page']['#title'] = t('Contextual filters');
              $form['settings']['override']['items_per_page']['#type'] = 'textfield';
              unset($form['settings']['override']['items_per_page']['#options']);
            }
          }
        }
      }
    }
  }
}

/**
 * Implementa hook_entity_view_alter().
 */
function icbf_migrations_entity_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  switch ($entity->getEntityTypeId()) {
    case 'taxonomy_term':
      // Add Layout Builder structure to Gestión Humana term.
      if ($entity->bundle() == 'sige_process_type' && $entity->id() == 6505) {
        $build['_layout_builder'][2] = $build['_layout_builder'][3];
      }
      // Remove Gestion Humana section in Layout builder to default.
      unset($build['_layout_builder'][3]);
      $build['_layout_builder']['#cache'] = NULL;
      break;
  }
}

/**
* Implements hook_prepare_row().
*/
function icbf_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $source = $row->getSource();
  $instances = $row->getSourceProperty('instances');
  if (isset($source['entity_type']) && $source['entity_type'] == 'comment') {
    $bundle = $row->getSourceProperty('bundle');
    $bundle = substr($bundle, 0, 32);
    $row->setSourceProperty('bundle', $bundle);
  }

  if (is_array($instances) && !empty($instances)) {
    $instance_changed = FALSE;
    foreach ($instances as $key => &$instance) {
      if ($instance['entity_type'] == 'comment') {
        $instance['bundle'] = substr($instance['bundle'], 0, 32);
        $instance_changed = TRUE;
      }
    }
    if ($instance_changed) {
      $row->setSourceProperty('instances', $instances);
    }
  }

  switch ($migration->id()) {
    case 'upgrade_d7_field':
    case 'upgrade_d7_field_instance':
    case 'upgrade_d7_field_instance_widget_settings':
      $type = $row->getSourceProperty('type');

      if ($type == 'text_long' || $type == 'text_with_summary') {
        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => $instance) {
          if (isset($instance['data'])) {
            $data = unserialize($instance['data']);
            if (isset($data['settings']['text_processing'])) {
              // Set all text processing to filtered text.
              $data['settings']['text_processing'] = 1;

              if (!empty($data['display'])) {
                foreach ($data['display'] as &$display_value) {
                  if ($display_value['type'] == 'text_glazed_builder') {
                    $display_value['type'] = 'text_default';
                    $display_value['module'] = 'text';
                  }
                }
              }

              $instance['data'] = serialize($data);
              $instances[$key] = $instance;
              $row->setSourceProperty('instances', $instances);
            }
          }
        }
      }
      elseif ($type == 'sarnia') {
        return FALSE;
      }

      // $bundle = $row->getSourceProperty('bundle');
      // if ($bundle == 'event' || $bundle == 'drag_drop_page' || $bundle == 'portfolio' || $bundle == 'cb_drag_drop_page') {
      //   return false;
      // }
      break;

    case 'upgrade_d7_comment_type':
      if (!$row->getSourceProperty('field_name')) {
        $row->setSourceProperty('field_name', 'comment_body');
      }
      break;

    case 'upgrade_d7_view_modes':
      $entity_type = $row->getSourceProperty('entity_type');
      if ($entity_type == 'sarnia_sarnia') {
        return FALSE;
      }
      elseif ($entity_type == 'bean') {
        $row->setSourceProperty('entity_type', 'block_content');
        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => $instance) {
          $instance['entity_type'] = 'block_content';
          $instances[$key] = $instance;
          $row->setSourceProperty('instances', $instances);
        }
      }
      break;

    case 'upgrade_d7_filter_format':
      if ($source['format'] == 'ds_code') {
        $row->setSourceProperty('format', 'ds_code');

        if ($row->hasSourceProperty('filters')) {
          $filters = $row->getSourceProperty('filters');
          $filters = [
            'php_code' => $filters['ds_code'],
          ];
          foreach ($filters as &$filter) {
            if (isset($filter['module']) && $filter['module'] === 'ds_format') {
              $filter = [
                'format' => 'ds_code',
                'module' => 'php',
                'name' => 'php_code',
                'weight' => '0',
                'status' => '1',
                'settings' => [],
              ];
            }
          }
          $row->setSourceProperty('filters', $filters);
        }
      }
      break;

    case 'upgrade_d7_node_complete_webform':
      // Assign default title to Webform nodes.
      if (!$row->hasSourceProperty('title') || empty($row->getSourceProperty('title'))) {
        $row->setSourceProperty('title', 'Webform sin título ' . $row->getSourceProperty('nid'));
      }
      break;

    case 'upgrade_d7_field_formatter_settings':
      $entity_type = $row->getSourceProperty('entity_type');
      $bundle = $row->getSourceProperty('bundle');
      $field_name = $row->getSourceProperty('field_name');
      $type = $row->getSourceProperty('type');
      $formatter = $row->getSourceProperty('formatter');
      $display = $row->getSourceProperty('display');

      if ($formatter['type'] == 'text_glazed_builder') {
        $formatter['type'] = 'text_default';
        $formatter['module'] = 'text';
        $row->setSourceProperty('formatter', $formatter);
      }
      elseif ($formatter['type'] == 'fivestar_formatter_default') {
        $formatter['type'] = 'fivestar_stars';
        $row->setSourceProperty('formatter', $formatter);
      }
      elseif ($formatter['type'] == 'slick') {
        $formatter['type'] = 'slick_image';
        $row->setSourceProperty('formatter', $formatter);
      }
      elseif ($formatter['type'] == 'extended_file_field' || $formatter['type'] == 'file_rendered') {
        $formatter['type'] = 'file_default';
        $row->setSourceProperty('formatter', $formatter);
      }
      elseif ($formatter['type'] == 'field_collection_fields') {
        $formatter['type'] = 'paragraph_summary';
        $row->setSourceProperty('formatter', $formatter);
      }

      if (isset($display['type']) && $display['type'] == 'text_glazed_builder') {
        $display['type'] = 'text_default';
        $display['module'] = 'text';
        $row->setSourceProperty('display', $display);
      }

      if ($type == 'text_long' || $type == 'text_with_summary') {
        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => $instance) {
          if (isset($instance['data'])) {
            $data = unserialize($instance['data']);
            if (isset($data['settings']['text_processing'])) {
              // Set all text processing to filtered text.
              $data['settings']['text_processing'] = 1;

              if (!empty($data['display'])) {
                foreach ($data['display'] as &$display_value) {
                  if ($display_value['type'] == 'text_glazed_builder') {
                    $display_value['type'] = 'text_default';
                    $display_value['module'] = 'text';
                  }
                }
              }
              $instance['data'] = serialize($data);
              $instances[$key] = $instance;
              $row->setSourceProperty('instances', $instances);
            }
          }
        }
      }

      // if ($bundle == 'event' || $bundle == 'drag_drop_page' || $bundle == 'portfolio' || $bundle == 'cb_drag_drop_page') {
      //   return false;
      // }

      if ($entity_type == 'bean') {
        $row->setSourceProperty('entity_type', 'block_content');
        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => &$instance) {
          if ($instance['entity_type'] == 'bean') {
            $instance['entity_type'] = 'block_content';
          }
        }
        $row->setSourceProperty('instances', $instances);

      }
      break;

    case 'upgrade_d7_bean_block':
      if (!$row->getSourceProperty('title')) {
        $label = $row->getSourceProperty('label');
        $row->setSourceProperty('title', $label);
      }
      break;

    case 'upgrade_d7_user_role':
      $permissions = $row->getSourceProperty('permissions');
      $permissions_to_remove = icbf_migrations_permissions_to_ignore();
      if (is_array($permissions) && !empty($permissions)) {
        foreach ($permissions as $key => $perm_name) {
          if (in_array($perm_name, $permissions_to_remove)) {
            unset($permissions[$key]);
          }
        }

        $row->setSourceProperty('permissions', $permissions);
      }
      break;

    case 'upgrade_d7_search404_settings':
      $search_path = $row->getSourceProperty('search404_custom_search_path');
      $search_path = str_replace('https://www.icbf.gov.co/', '', $search_path);
      $row->setSourceProperty('search404_custom_search_path', $search_path);
      break;

    case 'upgrade_d7_menu_links':
      if ($row->getSourceProperty('menu_name') == 'management') {
        return FALSE;
      }

      if ($source['plid'] == 1741 || $source['plid'] == 50) {
        $row->setSourceProperty('plid', 0);
      }

      if ($row->hasSourceProperty('link_path')) {
        $link_path = $row->getSourceProperty('link_path');

        if (strpos($link_path, 'node/') === 0) {
          $link_path = str_replace('node/', 'internal:/node/', $link_path);
        }
        elseif (strpos($link_path, 'taxonomy/term/') === 0) {
          $link_path = str_replace('taxonomy/term/', 'entity:taxonomy_term/', $link_path);
        }
        elseif (strpos($link_path, 'admin/') === 0) {
          $link_path = str_replace('admin/', 'internal:/admin/', $link_path);
        }
        elseif (strpos($link_path, 'citaciones/') === 0) {
          $link_path = str_replace('citaciones/', 'internal:/citaciones/', $link_path);
        }

        $row->setSourceProperty('link_path', $link_path);
      }
      elseif ($row->hasSourceProperty('parent_link_path')) {
        $link_path = $row->getSourceProperty('parent_link_path');

        if (strpos($link_path, 'admin/') === 0) {
          $link_path = str_replace('admin/', 'internal:/admin/', $link_path);
        }
        $row->setSourceProperty('parent_link_path', $link_path);
      }
      break;

    case 'upgrade_d7_views_migration':
      $views_id = [
        'usuarios',
        'editorial_last_content',
        'calendario_rendici_n',
        'taxonomy_term',
        'tranpsarencia_listado_temas',
        'glosario_icbf',
        'contexto_micrositios',
        'ada_home_grid',
        'micrositios_contextos',
        'documentos_contratacion',
        'ubicaciones_20',
        'tracker',
        'botones_home',
        'ni_os_migrantes_venezolanos',
        'me_conoces_ni_os_venezolanos',
        'proveedores',
        'media_browser_plus',
        'media_default',
        'informes_regionales_rendici_n_de_cuestas_',
        'sitemap',
        'notificaciones_pc_coactivos',
        'admin_views_node',
        'transparencia_home',
        'actas_contentivas_',
        'estudios_de_sector_v1',
        // 'calendar',
      ];
      if (in_array($source['name'], $views_id)) {
      }
      else {
        return FALSE;
      }
      break;
  }
}

/**
 * Implements icbf_migrations_permissions_to_ignore().
 */
function icbf_migrations_permissions_to_ignore() {
  $permissions = [
    'access administration menu',
    'access media browser',
    'allow CKFinder file uploads',
    'create files',
    'delete own audio files', 'download own audio files', 'edit own audio files',
    'delete own document files', 'download own document files', 'edit own document files',
    'delete own image files', 'download own image files', 'edit own image files',
    'delete own video files', 'download own video files', 'edit own video files',
    'geocoder_service_all_handlers',
    'geocoder_service_handler_bing',
    'geocoder_service_handler_exif',
    'geocoder_service_handler_google',
    'geocoder_service_handler_gpx',
    'geocoder_service_handler_json',
    'geocoder_service_handler_kml',
    'import media',
    'view any footer bean',
    'view revisions',
    'access all views',
    'access all webform results',
    'access bean overview',
    'access dashboard',
    'access example charts',
    'access flood unblock',
    'access own webform results',
    'access own webform submissions',
    'access sarnia entity pages',
    'access site map',
    'access statistics',
    'administer bean settings',
    'administer bean types',
    'administer beans',
    'administer charts',
    'administer ckeditor',
    'administer css injection',
    'administer ctools access ruleset',
    'administer entity view modes',
    'administer event status',
    'administer facetapi pretty paths',
    'administer features',
    'administer field collections',
    'administer fieldgroups',
    'administer fields',
    'administer file types',
    'administer files',
    'administer glazed builder configuration',
    'administer isotope',
    'administer layouts',
    'administer mailsystem',
    'administer md_megamenu',
    'administer media browser',
    'administer mini panels',
    'administer module filter',
    'administer page manager',
    'administer panel-nodes',
    'administer panelizer bean footer defaults',
    'administer panelizer bean tokens defaults',
    'administer panelizer comment comment_node_acta_contentiva defaults',
    'administer panelizer comment comment_node_agencies_adoptions_colombian defaults',
    'administer panelizer comment comment_node_announcement defaults',
    'administer panelizer comment comment_node_article defaults',
    'administer panelizer comment comment_node_articles_iin defaults',
    'administer panelizer comment comment_node_articles_portal_web defaults',
    'administer panelizer comment comment_node_articulo_nna defaults',
    'administer panelizer comment comment_node_banner_home defaults',
    'administer panelizer comment comment_node_blog defaults',
    'administer panelizer comment comment_node_curriculum_vitae defaults',
    'administer panelizer comment comment_node_document defaults',
    'administer panelizer comment comment_node_documentos_contrataci_n defaults',
    'administer panelizer comment comment_node_encargos defaults',
    'administer panelizer comment comment_node_encuesta_web defaults',
    'administer panelizer comment comment_node_enlaces_referencia defaults',
    'administer panelizer comment comment_node_enlaces_transparencia defaults',
    'administer panelizer comment comment_node_evaluaci_n defaults',
    'administer panelizer comment comment_node_event_calendar defaults',
    'administer panelizer comment comment_node_forum defaults',
    'administer panelizer comment comment_node_glosario defaults',
    'administer panelizer comment comment_node_hiring_process defaults',
    'administer panelizer comment comment_node_info_contexto defaults',
    'administer panelizer comment comment_node_infografia_observatorio defaults',
    'administer panelizer comment comment_node_informe_denuncias_anticorrupcion defaults',
    'administer panelizer comment comment_node_instituciones_adopciones defaults',
    'administer panelizer comment comment_node_local_shopping defaults',
    'administer panelizer comment comment_node_monitoreo_gesti_n defaults',
    'administer panelizer comment comment_node_multimedia defaults',
    'administer panelizer comment comment_node_news defaults',
    'administer panelizer comment comment_node_notifications defaults',
    'administer panelizer comment comment_node_page defaults',
    'administer panelizer comment comment_node_panel defaults',
    'administer panelizer comment comment_node_persona defaults',
    'administer panelizer comment comment_node_petition_rights defaults',
    'administer panelizer comment comment_node_photo_gallery2_event defaults',
    'administer panelizer comment comment_node_poll defaults',
    'administer panelizer comment comment_node_portfolio_tramite defaults',
    'administer panelizer comment comment_node_process defaults',
    'administer panelizer comment comment_node_rendicion_de_cuentas defaults',
    'administer panelizer comment comment_node_sector_studies defaults',
    'administer panelizer comment comment_node_sede_local defaults',
    'administer panelizer comment comment_node_services_faq defaults',
    'administer panelizer comment comment_node_summon defaults',
    'administer panelizer comment comment_node_summon_sdg defaults',
    'administer panelizer comment comment_node_tramites_vus defaults',
    'administer panelizer comment comment_node_transparency defaults',
    'administer panelizer comment comment_node_venta_de_bienes defaults',
    'administer panelizer comment comment_node_webform defaults',
    'administer panelizer file audio defaults administer panelizer file document defaults',
    'administer panelizer file image defaults',
    'administer panelizer file video defaults',
    'administer panelizer node acta_contentiva context',
    'administer panelizer node acta_contentiva overview',
    'administer panelizer node acta_contentiva settings',
    'administer panelizer node agencies_adoptions_colombian context',
    'administer panelizer node agencies_adoptions_colombian overview',
    'administer panelizer node agencies_adoptions_colombian settings',
    'administer panelizer node announcement context',
    'administer panelizer node announcement overview',
    'administer panelizer node announcement settings',
    'administer panelizer node article context',
    'administer panelizer node article overview',
    'administer panelizer node article settings',
    'administer panelizer node articles_iin context',
    'administer panelizer node articles_iin overview',
    'administer panelizer node articles_iin settings',
    'administer panelizer node articles_portal_web context',
    'administer panelizer node articles_portal_web overview',
    'administer panelizer node articles_portal_web settings',
    'administer panelizer node articulo_mis_manos_te_ensenan context',
    'administer panelizer node articulo_mis_manos_te_ensenan overview',
    'administer panelizer node articulo_mis_manos_te_ensenan settings',
    'administer panelizer node articulo_nna context',
    'administer panelizer node articulo_nna overview',
    'administer panelizer node articulo_nna settings',
    'administer panelizer node blog context',
    'administer panelizer node blog overview',
    'administer panelizer node blog settings',
    'administer panelizer node bot_n_home context',
    'administer panelizer node bot_n_home overview',
    'administer panelizer node bot_n_home settings',
    'administer panelizer node document context',
    'administer panelizer node document overview',
    'administer panelizer node document settings',
    'administer panelizer node document_microsite context',
    'administer panelizer node document_microsite overview',
    'administer panelizer node document_microsite settings',
    'administer panelizer node documento_de_convocatoria context',
    'administer panelizer node documento_de_convocatoria overview',
    'administer panelizer node documento_de_convocatoria settings',
    'administer panelizer node documento_multiple context',
    'administer panelizer node documento_multiple overview',
    'administer panelizer node documento_multiple settings',
    'administer panelizer node documentos_de_normativa context',
    'administer panelizer node documentos_de_normativa overview',
    'administer panelizer node documentos_de_normativa settings',
    'administer panelizer node enlaces_transparencia context',
    'administer panelizer node enlaces_transparencia overview',
    'administer panelizer node enlaces_transparencia settings',
    'administer panelizer node evaluaci_n context',
    'administer panelizer node evaluaci_n overview',
    'administer panelizer node evaluaci_n settings',
    'administer panelizer node event_calendar context',
    'administer panelizer node event_calendar overview',
    'administer panelizer node event_calendar settings',
    'administer panelizer node hiring_process context',
    'administer panelizer node hiring_process overview',
    'administer panelizer node hiring_process settings',
    'administer panelizer node info_contexto context',
    'administer panelizer node info_contexto overview',
    'administer panelizer node info_contexto settings',
    'administer panelizer node infografia_observatorio context',
    'administer panelizer node infografia_observatorio overview',
    'administer panelizer node infografia_observatorio settings',
    'administer panelizer node informe_denuncias_anticorrupcion context',
    'administer panelizer node informe_denuncias_anticorrupcion overview',
    'administer panelizer node informe_denuncias_anticorrupcion settings',
    'administer panelizer node instituciones_adopciones context',
    'administer panelizer node instituciones_adopciones overview',
    'administer panelizer node instituciones_adopciones settings',
    'administer panelizer node local_shopping context',
    'administer panelizer node local_shopping overview',
    'administer panelizer node local_shopping settings',
    'administer panelizer node monitoreo_gesti_n context',
    'administer panelizer node monitoreo_gesti_n overview',
    'administer panelizer node monitoreo_gesti_n settings',
    'administer panelizer node multimedia context',
    'administer panelizer node multimedia overview',
    'administer panelizer node multimedia settings',
    'administer panelizer node news context',
    'administer panelizer node news overview',
    'administer panelizer node news settings',
    'administer panelizer node notifications context',
    'administer panelizer node notifications overview',
    'administer panelizer node notifications settings',
    'administer panelizer node page context',
    'administer panelizer node page',
    'administer panelizer node page overview',
    'administer panelizer node page settings',
    'administer panelizer node petition_rights context',
    'administer panelizer node petition_rights overview',
    'administer panelizer node petition_rights settings',
    'administer panelizer node photo_gallery2_event context',
    'administer panelizer node photo_gallery2_event overview',
    'administer panelizer node photo_gallery2_event settings',
    'administer panelizer node process context',
    'administer panelizer node process overview',
    'administer panelizer node process settings',
    'administer panelizer node sector_studies context',
    'administer panelizer node sector_studies overview',
    'administer panelizer node sector_studies settings',
    'administer panelizer node sede_local context',
    'administer panelizer node sede_local overview',
    'administer panelizer node sede_local settings',
    'administer panelizer node summon context',
    'administer panelizer node summon overview',
    'administer panelizer node summon settings',
    'administer panelizer node summon_sdg context',
    'administer panelizer node summon_sdg overview',
    'administer panelizer node summon_sdg settings',
    'administer panelizer node transparency context',
    'administer panelizer node transparency overview',
    'administer panelizer node transparency settings',
    'administer panelizer taxonomy_term congreso_xxii context',
    'administer panelizer taxonomy_term congreso_xxii overview',
    'administer panelizer taxonomy_term congreso_xxii settings',
    'administer panelizer taxonomy_term eventos context',
    'administer panelizer taxonomy_term eventos overview',
    'administer panelizer taxonomy_term eventos settings',
    'administer panelizer taxonomy_term eventos_agenda context',
    'administer panelizer taxonomy_term eventos_agenda overview',
    'administer panelizer taxonomy_term eventos_agenda settings',
    'administer panelizer taxonomy_term hiring_process_type context',
    'administer panelizer taxonomy_term hiring_process_type overview',
    'administer panelizer taxonomy_term hiring_process_type settings',
    'administer panelizer taxonomy_term locations context',
    'administer panelizer taxonomy_term locations overview',
    'administer panelizer taxonomy_term locations settings',
    'administer panelizer taxonomy_term menu_observatory context',
    'administer panelizer taxonomy_term menu_observatory overview',
    'administer panelizer taxonomy_term menu_observatory settings',
    'administer panelizer taxonomy_term mis_manos_te_ensenan context',
    'administer panelizer taxonomy_term mis_manos_te_ensenan overview',
    'administer panelizer taxonomy_term mis_manos_te_ensenan settings',
    'administer panelizer taxonomy_term ninos_ninas_y_adolescentes context',
    'administer panelizer taxonomy_term ninos_ninas_y_adolescentes overview',
    'administer panelizer taxonomy_term ninos_ninas_y_adolescentes settings',
    'administer panelizer taxonomy_term para_papas context',
    'administer panelizer taxonomy_term para_papas overview',
    'administer panelizer taxonomy_term para_papas settings',
    'administer panelizer taxonomy_term procedure context',
    'administer panelizer taxonomy_term procedure overview',
    'administer panelizer taxonomy_term procedure settings',
    'administer panelizer taxonomy_term programa_adopciones context',
    'administer panelizer taxonomy_term programa_adopciones overview',
    'administer panelizer taxonomy_term programa_adopciones settings',
    'administer panelizer taxonomy_term secctions context',
    'administer panelizer taxonomy_term secctions overview',
    'administer panelizer taxonomy_term secctions settings',
    'administer panelizer taxonomy_term sige context',
    'administer panelizer taxonomy_term sige overview',
    'administer panelizer taxonomy_term sige settings',
    'administer panelizer taxonomy_term tags_tr_mites context',
    'administer panelizer taxonomy_term tags_tr_mites overview',
    'administer panelizer taxonomy_term tags_tr_mites settings',
    'administer panels display styles',
    'administer panels pane styles',
    'administer panels region styles',
    'administer respondjs',
    'administer sarnia entity types',
    'administer varnish',
    'administer video presets',
    'block IP addresses',
    'bypass access in place editing',
    'bypass conversion video',
    'bypass file access',
    'change layouts in place editing',
    'clone node',
    'clone own nodes',
    'configure_webform_charts',
    'context ajax block access',
    'control node view',
    'convert on submission',
    'create any footer bean',
    'create any js bean',
    'create any tokens bean',
    'create glosary content',
    'create mini panels',
    'customize ckeditor',
    'delete all webform submissions',
    'delete any audio files',
    'delete any document files',
    'delete any footer bean',
    'delete any image files',
    'delete any js bean',
    'delete any tokens bean',
    'delete any video files',
    'delete md_megamenu',
    'delete own document files',
    'delete own glosary content',
    'delete own webform submissions',
    'delete revisions',
    'delete terms in 1', 'delete terms in 10', 'delete terms in 12', 'delete terms in 13',
    'delete terms in 14', 'delete terms in 15', 'delete terms in 16', 'delete terms in 17',
    'delete terms in 18', 'delete terms in 19', 'delete terms in 21', 'delete terms in 22',
    'delete terms in 23', 'delete terms in 24', 'delete terms in 25', 'delete terms in 26',
    'delete terms in 27', 'delete terms in 28', 'delete terms in 29', 'delete terms in 3',
    'delete terms in 30', 'delete terms in 31', 'delete terms in 32', 'delete terms in 33',
    'delete terms in 34', 'delete terms in 35', 'delete terms in 36', 'delete terms in 37',
    'delete terms in 38', 'delete terms in 39', 'delete terms in 40', 'delete terms in 41',
    'delete terms in 42', 'delete terms in 44', 'delete terms in 45', 'delete terms in 46',
    'delete terms in 5', 'delete terms in 6', 'delete terms in 7', 'delete terms in 8', 'delete terms in 9',
    'diff view changes',
    'display drupal links',
    'download any audio files',
    'download any document files',
    'download any image files',
    'download any video files',
    'edit all webform submissions',
    'edit any audio files',
    'edit any document files',
    'edit any footer bean',
    'edit any image files',
    'edit any js bean',
    'edit any tokens bean',
    'edit any video files',
    'edit bean view mode',
    'edit meta tags',
    'edit own glosary content',
    'edit own webform submissions',
    'edit revisions',
    'edit terms in 1', 'edit terms in 10', 'edit terms in 12', 'edit terms in 13',
    'edit terms in 14', 'edit terms in 15', 'edit terms in 16', 'edit terms in 17',
    'edit terms in 18', 'edit terms in 19', 'edit terms in 21', 'edit terms in 22',
    'edit terms in 23', 'edit terms in 24', 'edit terms in 25', 'edit terms in 26',
    'edit terms in 27', 'edit terms in 28', 'edit terms in 29', 'edit terms in 3',
    'edit terms in 30', 'edit terms in 31', 'edit terms in 32', 'edit terms in 33',
    'edit terms in 34', 'edit terms in 35', 'edit terms in 36', 'edit terms in 37',
    'edit terms in 38', 'edit terms in 39', 'edit terms in 40', 'edit terms in 41',
    'edit terms in 42', 'edit terms in 44', 'edit terms in 45', 'edit terms in 46',
    'edit terms in 5', 'edit terms in 6', 'edit terms in 7', 'edit terms in 8', 'edit terms in 9',
    'edit via glazed builder',
    'edit webform components',
    'extended file field delete any file contents',
    'extended file field delete own file contents',
    'flush caches',
    'generate features',
    'generate pdf using mpdf',
    'geocoder_service_handler_latlon',
    'geocoder_service_handler_mapquest_nominatim',
    'geocoder_service_handler_openstreetmap_nominatim',
    'geocoder_service_handler_wkt',
    'geocoder_service_handler_yahoo',
    'geocoder_service_handler_yandex',
    'inspect all votes',
    'manage features',
    'opt-in or out of tracking',
    'override player dimensions',
    'publish any forum content',
    'publish editable forum content',
    'publish own forum content',
    'publish revisions',
    're convert video',
    'rename features',
    'revert revisions',
    'translate admin strings',
    'translate user-defined strings',
    'unpublish any forum content',
    'unpublish current revision',
    'unpublish editable forum content',
    'unpublish own forum content',
    'use PHP for label patterns',
    'use PHP for tracking visibility',
    'use ctools import',
    'use default thumb',
    'use page manager',
    'use panels in place editing',
    'use search_api_autocomplete for search_api_page_global_search',
    'use search_api_autocomplete for search_api_views_faqs_icbf',
    'use search_api_autocomplete for search_api_views_hiring_process',
    'use search_api_autocomplete for search_api_views_post_familias',
    'use search_api_autocomplete for search_api_views_tramites',
    'use search_api_autocomplete',
    'for search_api_views_ubicaciones',
    'use search_api_sorts',
    'use xmlsitemap',
    'use_search_api_live_results',
    'view any js bean',
    'view any tokens bean',
    'view bean page',
    'view bean revisions',
    'view files',
    'view own files',
    'view own private files',
    'view private files',
    'view revision status messages',
    'view_webform_charts ',
    'vote on polls',
    'use search_api_autocomplete for search_api_views_ubicaciones',
    'access backup and migrate',
    'access backup files',
    'access draggableviews',
    'access fieldable panels panes master list',
    'access memcache statistics',
    'access noticias search_api_page',
    'access overlay',
    'access printer-friendly version',
    'access printfriendly',
    'access search_api_page',
    'access slab cachedump',
    'add content to books',
    'administer backup and migrate',
    'administer book outlines',
    'administer breakpoints',
    'administer event colors',
    'administer fb_autopost',
    'administer fieldable panels panes',
    'administer geofield_gmap',
    'administer geofield_map configuration',
    'administer optimizedb settings',
    'administer page titles',
    'administer panelizer comment comment_node_carousel defaults',
    'administer panelizer comment comment_node_glosary defaults',
    'administer panelizer file audio defaults',
    'administer panelizer file document defaults',
    'administer panelizer node carousel defaults',
    'administer panelizer node file defaults',
    'administer panelizer node forum context',
    'administer panelizer node forum overview',
    'administer panelizer node forum settings',
    'administer panelizer node glosary defaults',
    'administer panelizer taxonomy_term category_content content',
    'administer panelizer taxonomy_term category_content context',
    'administer panelizer taxonomy_term category_content defaults',
    'administer panelizer taxonomy_term category_content layout',
    'administer panelizer taxonomy_term category_content overview',
    'administer panelizer taxonomy_term category_content settings',
    'administer panelizer taxonomy_term historias_de_usuario defaults',
    'administer panelizer taxonomy_term petition_rights_types defaults',
    'administer pictures',
    'administer printfriendly',
    'administer smart_ip',
    'audit_log_db_view_admin',
    'audit_log_filter_admin',
    'create carousel content',
    'create fieldable fieldable_panels_pane',
    'create file content',
    'create new books',
    'delete any carousel content',
    'delete any file content',
    'delete any glosary content',
    'delete backup files',
    'delete fieldable fieldable_panels_pane',
    'delete own carousel content',
    'delete own file content',
    'delete terms in 11', 'delete terms in 2', 'delete terms in 4',
    'edit terms in 11', 'edit terms in 2', 'edit terms in 4',
    'edit any carousel content',
    'edit any file content',
    'edit any glosary content',
    'edit fieldable fieldable_panels_pane',
    'edit own carousel content',
    'edit own file content',
    'perform backup',
    'restore from backup',
    'set facebook permissions',
    'set page title',
    'use text format buscarphp', 'use text format busv2f', 'use text format encontradosavanz',
    'use text format perfil_php_2', 'use text format php', 'use text format php_buscador',
    'use text format php_buscadoravanzado', 'use text format php_buscadorv2',
    'use text format php_buscar', 'use text format php_perfil_buscador',
    'view a11y simulations',
    'view any unpublished carousel content',
    'view_webform_charts',
    'create archivo content',
    'create location content',
    'delete own archivo content',
    'delete own location content',
    'edit own archivo content',
    'edit own location content',
    'publish any webform content',
    'publish editable webform content',
    'publish own webform content',
    'unpublish any webform content',
    'unpublish editable webform content',
    'unpublish own webform content'
  ];

  return $permissions;
}
